### ISSUE TITLE
Excellent config, but a tut would be helpful

### ISSUE THREAD

**Issue by zenny** [pprevos/emacs-config#1]
Hi Dr. @pprevos,

I am quite fascinated with this repository as well as your writings in lucidmanager site.

Meanwhile, I appreciate if you can write a tutorial on the current setup of yours. Particularly, the note-taking using denote and bibliography management with citar-denote and how you export the org files to a certain book template in your config. It could be extremely helpful to a lot of people, too.

Thanks in advance and have a nice weekend,
/z

**Comment by pprevos** [comment]
Hi Zenny,

I am glad the config and my website are helpful.

The good news is that I am updating my website and developing a starter kit called 'Emacs Writing Studio'. 

It will take me a couple of months to complete, so if you have any questions let me know. 

By the way, the [Denote manual](https://protesilaos.com/emacs/denote) by Prot is excellent.

Regards

P:)

**Comment by zenny** [comment]
> Hi Zenny,
> 
> I am glad the config and my website are helpful.
> 
> The good news is that I am updating my website and developing a starter kit called 'Emacs Writing Studio'.
> 
> It will take me a couple of months to complete, so if you have any questions let me know.
> 
> By the way, the [Denote manual](https://protesilaos.com/emacs/denote) by Prot is excellent.
> 
> Regards
> 
> P:)

Thanks, Dr. @pprevos:

Meanwhile would you mind to explain a brief on a few steps how do you export org-documents to different templates you created for books and papers. Appreciate that.

Your site is indeed useful. Thanks for the pointer to the Prot's Denote manual. 

Cheers,
/z

**Comment by pprevos** [comment]
Hi,

I have enhanced [my article on publishing articles and books with Org Mode](https://lucidmanager.org/productivity/publishing-with-org-mode-export/). Hope that helps a bit.

I am in the middle of developing a detailed website/book and configuration on using Emacs for writing books, so this is a work in progress.

Feel free to contact me if you have any questions so I can improve the document.

P:)

**Comment by zenny** [comment]
> Hi,
> 
> I have enhanced [my article on publishing articles and books with Org Mode](https://lucidmanager.org/productivity/publishing-with-org-mode-export/). Hope that helps a bit.

Certainly it was enjoyable read.

> 
> I am in the middle of developing a detailed website/book and configuration on using Emacs for writing books, so this is a work in progress.

Best of luck. 
> 
> Feel free to contact me if you have any questions so I can improve the document.
> 
> P:)

Thank Dr. @pprevos. I am just wondering how do you export to desired format to the templates described in https://github.com/pprevos/emacs-config/blob/7bac4d9d287413df00376a301a617df39327eefa/emacs-configuration.org?plain=1#L1242 onwards?!

Is there any org samples from your book to make realize the templates in https://github.com/pprevos/emacs-config/blob/7bac4d9d287413df00376a301a617df39327eefa/emacs-configuration.org?plain=1#L1242?

Cheers,
/z

**Comment by zenny** [comment]
> > Hi,
> > I have enhanced [my article on publishing articles and books with Org Mode](https://lucidmanager.org/productivity/publishing-with-org-mode-export/). Hope that helps a bit.
> 
> Certainly it was enjoyable read.
> 
> > I am in the middle of developing a detailed website/book and configuration on using Emacs for writing books, so this is a work in progress.
> 
> Best of luck.
> 
> > Feel free to contact me if you have any questions so I can improve the document.
> > P:)
> 
> Thank Dr. @pprevos. I am just wondering how do you export to desired format to the templates described in
> 
> https://github.com/pprevos/emacs-config/blob/7bac4d9d287413df00376a301a617df39327eefa/emacs-configuration.org?plain=1#L1242
> onwards?!
> 
> Is there any org samples from your book to make realize the templates in
> 
> https://github.com/pprevos/emacs-config/blob/7bac4d9d287413df00376a301a617df39327eefa/emacs-configuration.org?plain=1#L1242
> ?
> 
> Cheers, /z

I found the updated page you linked above, that read:

```
You can call this particular class by adding #+latex_class: apa6 to your file header. This mechanism empowers you to define bespoke LaTeX classes to create a library of export options.
```

Thanks anyway.
